KeysDictionary(
    'ag',
    (1, 11),
    Key('text', String(), help='Human oriented message string',),
    Key('version', String(), help='Actor version string',),
    Key('guideReady', Bool('0', '1'), help='Ready to guide',),
    Key('detectionState', Bool('0', '1'), help='Calculating guide offsets',),
    Key('exposureTime', Int(units='ms'), help='Exposure time',),
    Key('data',
        Float(name='ra', units='deg', help='Right ascension of field center'),
        Float(name='dec', units='deg', help='Declination of field center'),
        Float(name='pa', units='deg', help='Position angle of field'),
        String(name='guide', help='Guide objects'),
        String(name='detected', help='Detected objects'),
        String(name='identified', help='Identified objects'),
    ),
    Key('guideErrors',
        Int(name='exposureId', help='Exposure identifier'),
        Float(name='dRA', units='arcsec', help='Right ascension error'),
        Float(name='dDec', units='arcsec', help='Declination error'),
        Float(name='dInR', units='arcsec', help='Instrument rotator angle error'),
        Float(name='dAz', units='arcsec', help='Azimuth error'),
        Float(name='dAlt', units='arcsec', help='Altitude error'),
        Float(name='dZ', units='mm', help='Focus error'),
        Float(name='dScale', help='Scale error'),
    ),
    Key('focusErrors',
        Int(name='exposureId', help='Exposure identifier'),
        Float(name='dZ1', units='mm', help='Focus error (AGC1)'),
        Float(name='dZ2', units='mm', help='Focus error (AGC2)'),
        Float(name='dZ3', units='mm', help='Focus error (AGC3)'),
        Float(name='dZ4', units='mm', help='Focus error (AGC4)'),
        Float(name='dZ5', units='mm', help='Focus error (AGC5)'),
        Float(name='dZ6', units='mm', help='Focus error (AGC6)'),
    ),
    Key('guideOffsets',
        Float(name='dX', units='mm', help='X offset'),
        Float(name='dY', units='mm', help='Y offset'),
    ),
)
