KeysDictionary(
    'ag',
    (1, 9),
    Key('text', String(), help='Human oriented message string',),
    Key('version', String(), help='Actor version string',),
    Key('guideErrors',
        Int(name='exposureId', help='Exposure identifier'),
        Float(name='dRA', units='arcsec', help='Right ascension error'),
        Float(name='dDec', units='arcsec', help='Declination error'),
        Float(name='dInR', units='arcsec', help='Instrument rotator angle error'),
        Float(name='dAz', units='arcsec', help='Azimuth error'),
        Float(name='dAlt', units='arcsec', help='Altitude error'),
        Float(name='dZ', units='mm', help='Focus error'),
    ),
    Key('focusErrors',
        Int(name='exposureId', help='Exposure identifier'),
        Float(name='dZ1', units='mm', help='Focus error (AGC1)'),
        Float(name='dZ2', units='mm', help='Focus error (AGC2)'),
        Float(name='dZ3', units='mm', help='Focus error (AGC3)'),
        Float(name='dZ4', units='mm', help='Focus error (AGC4)'),
        Float(name='dZ5', units='mm', help='Focus error (AGC5)'),
        Float(name='dZ6', units='mm', help='Focus error (AGC6)'),
    ),
    Key('guideOffsets',
        Float(name='dX', units='mm', help='X offset'),
        Float(name='dY', units='mm', help='Y offset'),
    ),
)
