KeysDictionary('fvc', (1, 3),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key('exposureState1',
                   Enum('exposing','done', name="state"),
                   help='The current state of the exposure'),
               Key('exposureState2',
                   Enum('exposing','done', name="state"),
                   help='The current state of the exposure'),
               Key('exposureState3',
                   Enum('exposing','done', name="state"),
                   help='The current state of the exposure'),
               Key('exposureState4',
                   Enum('exposing','done', name="state"),
                   help='The current state of the exposure'),
               Key('exposureState5',
                   Enum('exposing','done', name="state"),
                   help='The current state of the exposure'),
               Key('exposureState6',
                   Enum('exposing','done', name="state"),
                   help='The current state of the exposure'),
)
