KeysDictionary('agcc', (1, 4),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key('agc1_stat', String(help='AG camera #1 status')),
               Key('agc2_stat', String(help='AG camera #2 status')),
               Key('agc3_stat', String(help='AG camera #3 status')),
               Key('agc4_stat', String(help='AG camera #4 status')),
               Key('agc5_stat', String(help='AG camera #5 status')),
               Key('agc6_stat', String(help='AG camera #6 status')),
               Key('agc_exposing', Int(help='total number of exposing AG cameras')),
               Key('agc_fitsname', String(help='Filename for combined AG camera images')),
               Key('agc1_fitsname', String(help='Filename for last AG camera #1 exposure')),
               Key('agc2_fitsname', String(help='Filename for last AG camera #2 exposure')),
               Key('agc3_fitsname', String(help='Filename for last AG camera #3 exposure')),
               Key('agc4_fitsname', String(help='Filename for last AG camera #4 exposure')),
               Key('agc5_fitsname', String(help='Filename for last AG camera #5 exposure')),
               Key('agc6_fitsname', String(help='Filename for last AG camera #6 exposure')),
)
