KeysDictionary("breva", (1, 3),
               Key('text', String(help='text for humans')),
               Key('version', String(help='EUPS/git version')),
               Key('hexaFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'MOVING', 'FAILED', name='substate'),
                   help='slit state machine'),
               Key("REPOBJ", Float(invalid="NaN", units="mm")*6,
                   help="repere objet par rapport nacelle "),
               Key("REPUTIL", Float(invalid="NaN", units="mm")*6,
                   help="repere utilisateur par rapport a machine"),              
               Key("position",
                   Float(name='X', help='x_coordinate'),
                   Float(name='Y', help='y_coordinate'),
                   Float(name='Z', help='z_coordinate'),
                   Float(name='U', help='u_coordinate'),
                   Float(name='V', help='v_coordinate'),
                   Float(name='W', help='w_coordinate'), help='breva current position'),
               Key('targetedFiber', String(help='Targeted fiber')),
               Key('error', Bool('0', '1', name='state', help='')),
               Key('in_pos', Bool('0', '1', name='state', help='')),
               Key('motors_on', Bool('0', '1', name='state', help='')),
               Key('homed', Bool('0', '1', name='state', help='')),
               Key('homing', Bool('0', '1', name='state', help='')),
               Key('above_limits', Bool('0', '1', name='state', help='')),
               Key('error_pursuit', Bool('0', '1', name='state', help='')),
               Key('error_variator', Bool('0', '1', name='state', help='')),
               Key('error_cinema', Bool('0', '1', name='state', help='')),
               Key('emergency_stop', Bool('0', '1', name='state', help='')),
               Key('unknown_error', Bool('0', '1', name='state', help='')),
               Key('no_init', Bool('0', '1', name='state', help='')),
               Key('no_comm', Bool('0', '1', name='state', help='')),
               Key('unvalid_mov', Bool('0', '1', name='state', help='')),
               Key('busy', Bool('0', '1', name='state', help='')),
               Key('asserv_failed', Bool('0', '1', name='state', help='')),
               Key('set_cfg_failed', Bool('0', '1', name='state', help='')),
               )


