KeysDictionary('ccd', (1,2),
               Key("Text", String(), help='Stuff for humans'),
               Key('version', String(help="CCD actor version",
                                     FITS=("W_RVCCD",
                                           "W_CCDACTOR_VERSION"))),
               Key('version_tron_actorcore', String(help="tron_actorcore version",
                                                    FITS=("W_RVACOR",
                                                          "W_ACTORCORE_VERSION"))),
               Key('version_ics_xcu_fpga', String(help="ics_xcu_fpga version",
                                                    FITS=("W_RVXFPG",
                                                          "W_XCU_FPGA_VERSION"))),
               Key('version_ics_actorkeys', String(help="ics_actorkeys version",
                                                   FITS=("W_RVAKEY",
                                                         "W_ACTORKEYS_VERSION"))),
               Key('version_fpga', String(help="FPGA firmware version",
                                          FITS=("W_RVFPGA",
                                                "W_FPGA_VERSION"))),
               Key('version_fee', String(help="FEE firmware version",
                                          FITS=("W_RVFEE",
                                                "W_FEE_VERSION"))),
               Key("ccdTemps",
                   Float(invalid="NaN", units="K", name='preamp'), 
                   Float(invalid="NaN", units="K", name='ccd0'), 
                   Float(invalid="NaN", units="K", name='ccd1'),
                   help='detector assembly temperatures'),

               Key("readRows",
                   Int(name='rowsDone'),
                   Int(name='rowsTotal'),
                   help="the number of rows read out and the image height."),

               Key("exposureState",
                   Enum('idle','wiping','integrating','reading','aborted','unknown'),
                   help="the state of the readout system"),

               Key("filepath",
                    String(name="rootDirectory"),
                    String(name="nightDirectory"),
                    String(name="filename"),
                    help="all the parts making up the image file path. Suitable for os.path.join()"),
)

