KeysDictionary('enu', (2, 4),
               Key('text', String(help='text for humans')),
               Key('version', String(help='EUPS/git version')),
               Key('metaFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'MOVING', 'EXPOSING', 'FAILED', name='substate'),
                   help='meta state machine'),

               Key('slitFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'MOVING', 'FAILED', name='substate'),
                   help='slit state machine'),
               Key('slitMode', Enum('operation', 'simulation', help='slit mode')),
               Key('slit',
                   Float(name='X', help='x_coordinate'),
                   Float(name='Y', help='y_coordinate'),
                   Float(name='Z', help='z_coordinate'),
                   Float(name='U', help='u_coordinate'),
                   Float(name='V', help='v_coordinate'),
                   Float(name='W', help='W_coordinate'), help='slit current position'),
               Key('slitHome',
                   Float(name='X', help='x_coordinate'),
                   Float(name='Y', help='y_coordinate'),
                   Float(name='Z', help='z_coordinate'),
                   Float(name='U', help='u_coordinate'),
                   Float(name='V', help='v_coordinate'),
                   Float(name='W', help='W_coordinate'), help='slit home coordinate system'),
               Key('slitTool',
                   Float(name='X', help='x_coordinate'),
                   Float(name='Y', help='y_coordinate'),
                   Float(name='Z', help='z_coordinate'),
                   Float(name='U', help='u_coordinate'),
                   Float(name='V', help='v_coordinate'),
                   Float(name='W', help='W_coordinate'), help='slit tool coordinate system'),
               Key('slitInfo', String(help='Hexapod controller status')),
               Key('slitLocation', String(help='FCA location')),

               Key('bshFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'EXPOSING', 'FAILED', name='substate'),
                   help='bsh state machine'),
               Key('bshMode', Enum('operation', 'simulation', help='bsh mode')),
               Key('shutters', Enum('close', 'open', 'openred', 'openblue', 'undef', name='position',
                                    help='shutters current position')),
               Key('shb',
                   Enum('close', 'open', name='open', help='blue shutter open bit'),
                   Enum('open', 'close', name='close', help='blue shutter close bit'),
                   Enum('ok', 'error', name='error', help='blue shutter error bit')),
               Key('shr',
                   Enum('close', 'open', name='open', help='red shutter open bit'),
                   Enum('open', 'close', name='close', help='red shutter close bit'),
                   Enum('ok', 'error', name='error', help='red shutter error bit')),

               Key('exptime', Float(help='exposure time in seconds')),
               Key('transientTime', Float(help='shutters transition time in seconds')),
               Key('integratingTime', Float(help='Shutter opening duration')),
               Key('elapsedTime', Float(help='Seconds since shutters opening')),
               Key('dateobs', String(help='absolute exposure start UTC time ISO formatted')),
               Key('bia', Enum('off', 'on', 'undef', name='state', help='bia current state')),
               Key('biaConfig',
                   Float(name='period', help='bia illumination period'),
                   Float(name='duty', help='duty cycle')),
               Key('biaStrobe',
                   Enum('off', 'on', name='state', help='strobe mode')),

               Key('rexmFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'MOVING', 'FAILED', name='substate'),
                   help='bsh state machine'),
               Key('rexmMode', Enum('operation', 'simulation', help='rexm mode')),
               Key('rexm',
                   Enum('low', 'mid', 'undef', name='position', help='rexm current position')),
               Key('rexmInfo',
                   UInt(name='switchA', help='switch A state'),
                   UInt(name='switchB', help='switch B state'),
                   Int(name='speed', help='motor speed ustep/sec'),
                   Int(name='steps', help='number of ustep from origin')),

               Key('tempsFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'FAILED', name='substate'),
                   help='temps state machine'),
               Key('tempsMode',  Enum('operation', 'simulation', help='temps mode')),
               Key('temps', Float(invalid='NaN', units='C') * 8, ),

               Key('pduFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'FAILED', name='substate'),
                   help='pdu state machine'),
               Key('pduMode',  Enum('operation', 'simulation', help='pdu mode')),

               Key('iisFSM',
                   Enum('OFF', 'LOADED', 'ONLINE', name='state'),
                   Enum('IDLE', 'LOADING', 'INITIALISING', 'FAILED', name='substate'),
                   help='iis state machine'),
               Key('iisMode',  Enum('operation', 'simulation', help='iis mode')),

               )
