KeysDictionary('enu', (1, 3),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key("ENUState",
                   Enum('LOADED', 'INITIALIZING', 'IDLE', 'BUSY', 'FAILED'),
                   help='ENU current state'),
               Key("BIAState",
                   Enum('LOADED', 'INITIALIZING', 'IDLE', 'BUSY', 'FAILED'),
                   help='BIA current state'),
               Key("BIAPosition",
                   Enum('on', 'off'),
                   help='BIA current position'),
               Key("ShutterState",
                   Enum('LOADED', 'INITIALIZING', 'IDLE', 'BUSY', 'FAILED'),
                   help='Shutter current state'),
               Key("ShutterPosition",
                   Enum('open', 'close'),
                   help='Shutter current position'),
               Key("SlitState",
                   Enum('LOADED', 'INITIALIZING', 'IDLE', 'BUSY', 'FAILED'),
                   help='BIA current state'),
               Key("SlitPosition,",
                   Enum('X', 'Y', 'Z', 'U', 'V', 'W'),
                   help='BIA current position'),
               )
