KeysDictionary('fps', (1, 4),
               Key("text", String(help="text for humans")),
               Key('version', String(help="FPS actor version",
                                     FITS=("W_RVFPS",
                                           "W_FPSACTOR_VERSION"))),
               Key('version_tron_actorcore', String()),
               Key('version_pfs_utils', String()),
               Key('mcsBoresight', Float(name='x'), Float(name='y')),
               Key('pfsDesignId', Long(help="the loaded pfsDesignId",
                                       FITS=('W_PFDSGN', 'W_PFS_DESIGN_ID'))),
               Key('pfsConfig',
                   Long(name='pfsDesign', help='the pfsDesign we are working on'),
                   Long(name='pfsConfig', help='the current pfsConfig for the PFI',
                        FITS=('W_PFSCFG', 'W_PFS_CONFIG_ID')),
                   Int(name='visit0', help='the visit0 for the convergence'),
                   String(name='ConvergenceStatus', help='the current convergence status')),
)
