KeysDictionary('fvc', (1, 3),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key("model", String(help="camera model and serial numner")),
               Key("exptime", Float(help="exposure time for one frame", units="us")),
               Key("gain", Float(help="readout gain", units="dB")),
               Key('exposureState',
                   Enum('exposing','done', name="state"),
                   help='The current state of the exposure'),
               Key('filename', String(help='name of just finished exposure')),
)
