KeysDictionary("idg", (1, 3),
               Key('Text', String(), help='Stuff for humans'),

               Key("testRanges",
                   String(name='cameraName'),
                   Int(name="a", invalid="NaN", units="steps", help='range of axis A'),
                   Int(name="b", invalid="NaN", units="steps", help='range of axis B'),
                   Int(name="c", invalid="NaN", units="steps", help='range of axis C'),
                   help="End-to-end range of the FPA motors."),

               Key("testOffsets",
                   String(name='cameraName'),
                   Int(name='loopCount', help='test loop count'),
                   Int(name='a', invalid="NaN", units="steps", help='error of axis A'),
                   Int(name='b', invalid="NaN", units="steps", help='error of axis B'),
                   Int(name='c', invalid="NaN", units="steps", help='error of axis C'),
                   help="Post-cycle error of the FPA motors."),

               Key("nirLed",
                   Float(name="wavelength",
                         FITS=("W_JNWAVE", "JHU_NIR_LED_WAVELENGTH"),
                         help="NIR cleanroom LED wavelength",
                         units="nm"),
                   Float(name="dutyCycle",
                         FITS=("W_JNCYCL", "JHU_NIR_LED_DUTYCYCLE"),
                         help="NIR cleanroom LED dutycycle",
                         units="%")),
               
               Key("nirStage",
                   Int(name="xsteps",
                       FITS=("W_JNXSTP", "JHU_NIR_XSTEPS"),
                       help="NIR cleanroom stage X steps"),
                   Int(name="ysteps",
                       FITS=("W_JNYSTP", "JHU_NIR_YSTEPS"),
                       help="NIR cleanroom stage Y steps"),
                   Float(name="xpix",
                         FITS=("W_JNXPIX", "JHU_NIR_XPIX"),
                         help="approx. NIR stage X pix"),
                   Float(name="ypix",
                         FITS=("W_JNYPIX", "JHU_NIR_YPIX"),
                         help="approx. NIR stage Y pix")),

               Key("thermalTemps",
                   Float(name='body1', invalid="NaN", units="K", help="IDG CR Cryostat body temp 1", FITS=("W_TPTMP1", "IDG_THERMAL_PLATE_TEMP_1")),
                   Float(name='body2', invalid="NaN", units="K", help="IDG CR Cryostat body temp 2", FITS=("W_TPTMP2", "IDG_THERMAL_PLATE_TEMP_2")),
                   Float(name='body3', invalid="NaN", units="K", help="IDG CR Cryostat body temp 3", FITS=("W_TPTMP3", "IDG_THERMAL_PLATE_TEMP_3")),
                   Float(name='body4', invalid="NaN", units="K", help="IDG CR Cryostat body temp 4", FITS=("W_TPTMP4", "IDG_THERMAL_PLATE_TEMP_4")),
                   Float(name='roomAir', invalid="NaN", units="K", help="IDG CR room air", FITS=("W_TPTMP5", "IDG_THERMAL_PLATE_ROOMTEMP_1")),
                   Float(name='roomAir2', invalid="NaN", units="K", help="IDG CR room air", FITS=("W_TPTMP6", "IDG_THERMAL_PLATE_ROOMTEMP_2")),
                   help="IDG NIR cleanroom thermal plate temps"),
)
