KeysDictionary("idg", (1, 2),
               Key('Text', String(), help='Stuff for humans'),

               Key("testRanges",
                   String(name='camera name'),
                   Int(invalid="NaN", units="steps", name='range of axis A'), 
                   Int(invalid="NaN", units="steps", name='range of axis B'), 
                   Int(invalid="NaN", units="steps", name='range of axis C'), 
                   help="End-to-end range of the FPA motors."),

               Key("testOffsets",
                   String(name='camera name'),
                   Int(name='test loop count'), 
                   Int(invalid="NaN", units="steps", name='error of axis A'), 
                   Int(invalid="NaN", units="steps", name='error of axis B'), 
                   Int(invalid="NaN", units="steps", name='error of axis C'), 
                   help="Post-cycle error of the FPA motors."),

               Key("nirLed",
                   Float(name="wavelength",
                         FITS=("W_JNWAVE", "JHU_NIR_LED_WAVELENGTH"),
                         help="NIR cleanroom LED wavelength",
                         units="nm"),
                   Float(name="dutyCycle",
                         FITS=("W_JNCYCL", "JHU_NIR_LED_DUTYCYCLE"),
                         help="NIR cleanroom LED dutycycle",
                         units="%")),
               
               Key("nirStage",
                   Int(name="xsteps",
                       FITS=("W_JNXSTP", "JHU_NIR_XSTEPS"),
                       help="NIR cleanroom stage X steps"),
                   Int(name="ysteps",
                       FITS=("W_JNYSTP", "JHU_NIR_YSTEPS"),
                       help="NIR cleanroom stage Y steps"),
                   Float(name="xpix",
                         FITS=("W_JNXPIX", "JHU_NIR_XPIX"),
                         help="approx. NIR stage X pix"),
                   Float(name="ypix",
                         FITS=("W_JNYPIX", "JHU_NIR_YPIX"),
                         help="approx. NIR stage Y pix")),
)
