KeysDictionary('iic', (1, 10),
               Key("controllers", String(help='controllers list') * (1, None)),
               Key("text", String(), help='Stuff for humans'),
               Key('version', String(help="IIC actor version",
                                     FITS=("W_RVIIC",
                                           "W_IICACTOR_VERSION"))),
               Key('version_tron_actorcore', String(help="tron_actorcore version")),
               Key('version_ics_actorkeys', String(help="ics_actorkeys version")),
               Key('version_pfs_utils', String(help="pfs_utils version")),

               Key("sequence",
                   Int(name='sequenceId'),
                   Int(name='groupId'),
                   String(name='sequenceType'),
                   String(name='name'),
                   String(name='comments'),
                   String(name='cmdStr'),
                   Enum('active', 'failed', 'finished', 'aborted', name='status'),
                   String(name='output'),
                   help='data acquisition sequence'),

               Key("subCommand",
                   Int(name='sequenceId'),
                   Int(name='cmdId'),
                   String(name='cmdStr'),
                   Bool('0', '1', name='didFail'),
                   String(name='lastReply'),
                   help='subCommand from sps_sequence'),

               Key("designId",
                   Long(name="mask", reprFmt="0x%016x")),
               Key("pfsDesign",
                   Long(name="designId", reprFmt="0x%016x"),
                   Int(name="visit"),
                   Float(name="ra", reprFmt="%0.6f"),
                   Float(name="dec", reprFmt="%0.6f"),
                   Float(name="pa", reprFmt="%0.6f"),
                   String(name="name"),
                   Long(name="designId0", reprFmt="0x%016x"),
                   Int(name="variant")),
               Key("pfsConfig0",
                   Long(name="designId", reprFmt="0x%016x"),
                   Int(name="visit0"),
                   String(name="dateDir"),
                   Float(name="ra", reprFmt="%0.6f"),
                   Float(name="dec", reprFmt="%0.6f"),
                   Float(name="pa", reprFmt="%0.6f"),
                   String(name="name"),
                   Long(name="designId0", reprFmt="0x%016x"),
                   Int(name="variant")),
               Key("pfsConfig",
                   Long(name="designId", reprFmt="0x%016x"),
                   Int(name="visit"),
                   String(name="dateDir"),
                   Float(name="ra", reprFmt="%0.6f"),
                   Float(name="dec", reprFmt="%0.6f"),
                   Float(name="pa", reprFmt="%0.6f"),
                   String(name="name"),
                   Long(name="designId0", reprFmt="0x%016x"),
                   Int(name="variant")),

               Key("pfsVisit",
                   Int(name="spsVisit", help="current sps visit")),
               Key("groupId",
                   Int(name="gid", help="groupId"),
                   String(name="name", help="groupName"))

               )
