KeysDictionary('iic', (1,3),
               Key("controllers", String(help='controllers list') * (1, None)),
               Key("text", String(), help='Stuff for humans'),
               Key('version', String(help="IIC actor version",
                                     FITS=("W_RVIIC",
                                           "W_IICACTOR_VERSION"))),
               Key('version_tron_actorcore', String(help="tron_actorcore version")),
               Key('version_ics_actorkeys', String(help="ics_actorkeys version")),
               Key('version_pfs_utils', String(help="pfs_utils version")),

               Key("sps_sequence",
                   Int(name='sequenceId'),
                   String(name='sequenceType'),
                   String(name='cmdStr'),
                   String(name='name'),
                   String(name='comments'),
                   Bool('False', 'True', name='isDone'),
                   help='sps_sequence'),

               Key("subCommand",
                   Int(name='sequenceId'),
                   Int(name='cmdId'),
                   String(name='cmdStr'),
                   Bool('0', '1', name='didFail'),
                   String(name='lastReply'),
                   help='subCommand from sps_sequence'),
)