KeysDictionary("iis", (1, 2),
               Key("text", String(), help='Stuff for humans'),
               Key('version', String(help="iis actor version",
                                     FITS=("W_RVIIS",
                                           "IISACTOR_VERSION"))),
               Key('version_tron_actorcore', String(help="tron_actorcore version")),
               Key('version_pfs_instdata', String(help="pfs_instdata version")),

               Key('lampStatus', Enum("off", "warming", "ready", "on", "unknown",
                                      help="state of the entire IIS controller.")),
               Key('modules', String(help="connected SMs")),

               Key('lampRequestMask',
                   Bool('off', 'on', name='ne', help='Neon lamp was on',
                        FITS=('W_IISNEO', 'IIS_NEON_LAMP_STATE')),
                   Bool('off', 'on', name='ar', help='Argon lamp was on',
                        FITS=('W_IISARG', 'IIS_ARGON_LAMP_STATE')),
                   Bool('off', 'on', name='kr', help='Krypton lamp was on',
                        FITS=('W_IISKRY', 'IIS_KRYPTON_LAMP_STATE')),
                   Bool('off', 'on', name='hgar', help='HgAr lamp was on',
                        FITS=('W_IISHGA', 'IIS_HGAR_LAMP_STATE')),
                   Bool('off', 'on', name='h', help='Hydrogen lamp was on',
                        FITS=('W_IISHYD', 'IIS_HYD_LAMP_STATE')),
                   Bool('off', 'on', name='he', help='Helium lamp was on',
                        FITS=('W_IISHE', 'IIS_HE_LAMP_STATE')),
                   Bool('off', 'on', name='cont', help='Halogen lamp was on',
                        FITS=('W_IISQTH', 'IIS_HALOGEN_LAMP_STATE'))),
               Key('lampRequestTimes',
                   Int(name='ne', help='Neon lamp request time',
                       FITS=('W_ISNEOT', 'IIS_NEON_TIME')),
                   Int(name='ar', help='Argon lamp request time',
                       FITS=('W_ISARGT', 'IIS_ARGON_TIME')),
                   Int(name='kr', help='Krypton lamp request time',
                       FITS=('W_ISKRYT', 'IIS_KRYPTON_TIME')),
                   Int(name='hgar', help='HgAr lamp request time',
                       FITS=('W_ISHGAT', 'IIS_HGAR_TIME')),
                   Int(name='h', help='Hydrogen lamp request time',
                       FITS=('W_ISHYDT', 'IIS_HYD_TIME')),
                   Int(name='he', help='Helium lamp request time',
                       FITS=('W_ISHET', 'IIS_HE_TIME')),
                   Int(name='cont', help='Halogen lamp request time',
                       FITS=('W_ISQTHT', 'IIS_HALOGEN_TIME'))),
               Key('halogen',
                   Bool('off', 'on', name='state', help='Halogen lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
               Key('neon',
                   Bool('off', 'on', name='state', help='Neon lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
               Key('argon',
                   Bool('off', 'on', name='state', help='Argon lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('krypton',
                   Bool('off', 'on', name='state', help='Krypton lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('hgar',
                   Bool('off', 'on', name='state', help='HgAr lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('hydrogen',
                   Bool('off', 'on', name='state', help='Hydrogen lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('helium',
                   Bool('off', 'on', name='state', help='Helium lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
)
