KeysDictionary("iis", (1, 3),
               Key("text", String(), help='Stuff for humans'),
               Key('version', String(help="iis actor version",
                                     FITS=("W_RVIIS",
                                           "IISACTOR_VERSION"))),
               Key('version_tron_actorcore', String(help="tron_actorcore version")),
               Key('version_pfs_instdata', String(help="pfs_instdata version")),

               Key('lampStatus', Enum("off", "warming", "ready", "on", "unknown",
                                      help="state of the entire IIS controller.")),
               Key('modules', String(help="connected SMs")),

               Key('lampRequestMask',
                   Bool('off', 'on', name='ne', help='Neon lamp was on'),
                   Bool('off', 'on', name='ar', help='Argon lamp was on'),
                   Bool('off', 'on', name='kr', help='Krypton lamp was on'),
                   Bool('off', 'on', name='hgar', help='HgAr lamp was on'),
                   Bool('off', 'on', name='h', help='Hydrogen lamp was on'),
                   Bool('off', 'on', name='he', help='Helium lamp was on'),
                   Bool('off', 'on', name='cont', help='Halogen lamp was on')),
               Key('lampRequestTimes',
                   Int(name='ne', help='Neon lamp request time'),
                   Int(name='ar', help='Argon lamp request time'),
                   Int(name='kr', help='Krypton lamp request time'),
                   Int(name='hgar', help='HgAr lamp request time'),
                   Int(name='h', help='Hydrogen lamp request time'),
                   Int(name='he', help='Helium lamp request time'),
                   Int(name='cont', help='Halogen lamp request time')),
               Key('halogen',
                   Bool('off', 'on', name='state', help='Halogen lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
               Key('neon',
                   Bool('off', 'on', name='state', help='Neon lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
               Key('argon',
                   Bool('off', 'on', name='state', help='Argon lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('krypton',
                   Bool('off', 'on', name='state', help='Krypton lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('hgar',
                   Bool('off', 'on', name='state', help='HgAr lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('hydrogen',
                   Bool('off', 'on', name='state', help='Hydrogen lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('helium',
                   Bool('off', 'on', name='state', help='Helium lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
)
