KeysDictionary('mcs', (1, 6),
               Key("text", String(help="text for humans")),
               Key('version', String(help="MCS actor version",
                                     FITS=("W_RVMCS",
                                           "W_MCSACTOR_VERSION"))),
               Key('version_tron_actorcore', String()),
               Key('version_pfs_utils', String()),
               Key("cameraName", String()),
               Key("readNoise", Float(help="nominal readnoise for camera", units="e-")),
               Key("centroidsChunk", String(help="base64 encoded centroids")),
               Key('exposureState',
                   Enum('IDLE','FLUSHING','INTEGRATING','READING','ABORTED','DONE', name="state"),
                   help='The current state of the exposure'),
               Key('filename', String(help='name of just finished exposure')),
)
