KeysDictionary('meb', (1, 6),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key('temps',
                      Float(name='Top_plate', units='degC'),
                      Float(name='Carbon_fiber_tube', units='degC'),
                      Float(name='Primary_mirror', units='degC'),
                      Float(name='Cover_panel', units='degC'),
                      Float(name='Coolant_water_in', units='degC'),
                      Float(name='Coolant_water_out', units='degC'),
                      Float(name='Electronic_rack', units='degC'),
                   help='MCS Ebox temperatures'),
               Key('power',
                      Int(name='Camera', units='V'),
                      Int(name='Shutter_and_Temp', units='V'),
                      Int(name='Cisco_switch', units='V'),
                      Int(name='MCS_computer', units='V'),
                   help='MCS power status'),
               Key('flow',
                      Float(name='Flow_meter', units='Hz'),
                   help='Flow meter reading'),
)
