KeysDictionary('meb', (1, 5),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key('temps', Float()*7,
                   help='MCS Ebox temperatures'),
               Key('power', Int()*4,
                   help='MCS power status'),
               Key('flow', Float(),
                   help='Flow meter for MCS'),
)
