KeysDictionary(
    'mlp1',
    (1, 2),
    Key('text', String(), help='Human oriented message string',),
    Key('version', String(), help='Actor version string',),
    Key('telescopeState',
        Bool('0', '1', name='mount_if_fault', help='',),
        Bool('0', '1', name='rotator_if_fault', help='',),
        Float(name='az_el_detect_time', units='s', help='',),
        Float(name='az_real_angle', units='deg', help='',),
        Float(name='el_real_angle', units='deg', help='',),
        Float(name='rotator_real_angle', units='deg', help='',),
        Bool('0', '1', name='ag_if_alarm', help='',),
        Bool('0', '1', name='tsc_fault', help='',),
        help='',
    ),
    Key('guideError',
        Float(name='azimuth', units='arcsec', help='',),
        Float(name='elevation', units='arcsec', help='',),
        help='',
    ),
)
