KeysDictionary('peb', (1, 1),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key('temps', Float()*21,
                   help='The PFI Ebox temperatures'),
               Key('humidity', Float()*3,
                   help='The PFI Ebox humidity, temperature and dew point'),
               Key('flow', Float(),
                   help='The PFI Ebox flow meter'),
               Key('leakage', Int()*2,
                   help='The PFI Ebox leakage and detector disconnect status'),
               Key('ledperiod', Int()*3,
                   help='The PFI Ebox LED peroid in us'),
               Key('dutycycle', Float()*3,
                   help='The PFI Ebox LED dutycycle in %'),
               Key('power', Int()*13,
                   help='The PFI Ebox power status'),
)
