KeysDictionary('peb', (1, 4),
               Key("text", String(help="text for humans")),
               Key("version", String(help="EUPS/git version")),
               Key('temps',
                      Float(name='AGC_4', units='degC'),
                      Float(name='AGC_3', units='degC'),
                      Float(name='AGC_2', units='degC'),
                      Float(name='AGC_1', units='degC'),
                      Float(name='AGC_6', units='degC'),
                      Float(name='AGC_5', units='degC'),
                      Float(name='UL_link_1', units='degC'),
                      Float(name='UL_link_2', units='degC'),
                      Float(name='UL_link_3', units='degC'),
                      Float(name='Positioner_frame', units='degC'),
                      Float(name='COB_1', units='degC'),
                      Float(name='COB_2', units='degC'),
                      Float(name='COB_3', units='degC'),
                      Float(name='COB_4', units='degC'),
                      Float(name='COB_5', units='degC'),
                      Float(name='COB_6', units='degC'),
                      Float(name='Ebox_1', units='degC'),
                      Float(name='Ebox_2', units='degC'),
                      Float(name='Ebox_3', units='degC'),
                      Float(name='Flow_in', units='degC'),
                      Float(name='Flow_out', units='degC'),
                   help='PFI Ebox temperatures'),
               Key('humidity',
                      Float(name='Humidity', units='%', STS=0, help='helpful description'),
                      Float(name='Temperature', units='degC', STS=1, help='helpful description'),
                      Float(name='Dew_point', units='degC', STS=2, help='helpful description'),
                   help='PFI Ebox humidity sensor SHT75'),
               Key('flow',
                      Float(name='Flow_meter', units='Gal/min'),
                      Float(name='Flow_rotor', units='Hz'),
                   help='PFI Ebox flow meter'),
               Key('leakage',
                      Int(name='Leakage', units='bool'),
                      Int(name='Disconnect', units='bool'),
                   help='PFI Ebox leakage sensor'),
               Key('ledperiod',
                      Int(name='Now', units='uS'),
                      Int(name='On', units='uS'),
                      Int(name='Flash', units='uS'),
                   help='PFI Ebox LED peroid'),
               Key('dutycycle',
                      Float(name='Now', units='%'),
                      Float(name='On', units='%'),
                      Float(name='Flash', units='%'),
                   help='PFI Ebox LED dutycycle'),
               Key('power',
                      Int(name='AGC_1', units='V'),
                      Int(name='AGC_2', units='V'),
                      Int(name='AGC_3', units='V'),
                      Int(name='AGC_4', units='V'),
                      Int(name='AGC_5', units='V'),
                      Int(name='AGC_6', units='V'),
                      Int(name='Leakage', units='V'),
                      Int(name='Adam6015', units='V'),
                      Int(name='USB_1', units='V'),
                      Int(name='USB_2', units='V'),
                      Int(name='Flow_board', units='V'),
                      Int(name='LED_board', units='V'),
                      Int(name='Switch', units='V'),
                   help='PFI Ebox power status'),
)
