KeysDictionary("pfilamps", (1, 0),
               Key("controllers", String(help='controllers list') * (1, 2)),
               Key("text", String(), help='Stuff for humans'),
               Key('version', String(help="pfilamps actor version",
                                     FITS=("W_RVPFIL",
                                           "W_PFILAMPSACTOR_VERSION"))),
               Key('version_tron_actorcore', String(help="tron_actorcore version")),

               Key('lampStatus', Enum("off", "warming", "ready", "on", "unknown",
                                      help="state of the entire PFI lamp controller.")),

               # [ar=S] [hgcd=S] [kr=S] [ne=S] [xe=S] [qth=S]
               Key('lampRequest',
                   Float("ar",
                         help="Argon lamp requested time",
                         FITS=("W_CLART",
                               "W_PFILAMPS_ARGON_TIME")),
                   Float("hgcd",
                         help="HgCd lamp requested time",
                         FITS=("W_CLHGCT",
                               "W_PFILAMPS_HGCD_TIME")),
                   Float("kr",
                         help="Krypton lamp requested time",
                         FITS=("W_CLKRT",
                               "W_PFILAMPS_KRYPTON_TIME")),
                   Float("ne",
                         help="Neon lamp requested time",
                         FITS=("W_CLNET",
                               "W_PFILAMPS_NEON_TIME")),
                   Float("xe",
                         help="Xenon lamp requested time",
                         FITS=("W_CLXET",
                               "W_PFILAMPS_XENON_TIME")),
                   Float("qth",
                         help="Quartz-halogen lamp requested time",
                         FITS=("W_CLQTHT",
                               "W_PFILAMPS_QTH_TIME"))),

               Key('lampIntensity',
                   Float("ar",
                         help="Argon lamp measured voltage",
                         FITS=("W_CLARV",
                               "W_PFILAMPS_ARGON_VOLTAGE")),
                   Float("hg",
                         help="Hg lamp line measured voltage",
                         FITS=("W_CLHGV",
                               "W_PFILAMPS_HG_VOLTAGE")),
                   Float("cd",
                         help="Cd lamp line measured voltage",
                         FITS=("W_CLCDV",
                               "W_PFILAMPS_CD_VOLTAGE")),
                   Float("kr",
                         help="Krypton lamp measured voltage",
                         FITS=("W_CLKRV",
                               "W_PFILAMPS_KRYPTON_VOLTAGE")),
                   Float("ne",
                         help="Neon lamp measured voltage",
                         FITS=("W_CLNEV",
                               "W_PFILAMPS_NEON_VOLTAGE")),
                   Float("xe",
                         help="Xenon lamp measured voltage",
                         FITS=("W_CLXEV",
                               "W_PFILAMPS_XENON_VOLTAGE")),
                   Float("qth",
                         help="Quartz-halogen lamp measured voltage",
                         FITS=("W_CLQTHV",
                               "W_PFILAMPS_QTH_VOLTAGE"))),
)
