KeysDictionary("pfilamps", (2, 2),
               Key("text", String(), help='Stuff for humans'),
               Key('version', String(help="pfilamps actor version",
                                     FITS=("W_RVPFIL",
                                           "PFILAMPSACTOR_VERSION"))),
               Key('version_tron_actorcore', String(help="tron_actorcore version")),

               Key('lampStatus', Enum("off", "warming", "ready", "on", "unknown",
                                      help="state of the entire PFI lamp controller.")),

               Key('lampRequestMask',
                   Bool('off', 'on', name='ne', help='Neon lamp was on',
                        FITS=('W_AITNEO', 'NEON_LAMP_STATE')),
                   Bool('off', 'on', name='ar', help='Argon lamp was on',
                        FITS=('W_AITARG', 'ARGON_LAMP_STATE')),
                   Bool('off', 'on', name='kr', help='Krypton lamp was on',
                        FITS=('W_AITKRY', 'KRYPTON_LAMP_STATE')),
                   Bool('off', 'on', name='xe', help='Xenon lamp was on',
                        FITS=('W_AITXEN', 'XENON_LAMP_STATE')),
                   Bool('off', 'on', name='hgcd', help='HgCd lamp was on',
                        FITS=('W_AITHGC', 'HGCD_LAMP_STATE')),
                   Bool('off', 'on', name='cont', help='Halogen lamp was on',
                        FITS=('W_AITQTH', 'HALOGEN_LAMP_STATE'))),
               Key('lampRequestTimes',
                   Int(name='ne', help='Neon lamp request time',
                       FITS=('W_CLNEOT', 'PFILAMPS_NEON_TIME')),
                   Int(name='ar', help='Argon lamp request time',
                       FITS=('W_CLARGT', 'PFILAMPS_ARGON_TIME')),
                   Int(name='kr', help='Krypton lamp request time',
                       FITS=('W_CLKRYT', 'PFILAMPS_KRYPTON_TIME')),
                   Int(name='xe', help='Xenon lamp request time',
                       FITS=('W_CLXENT', 'PFILAMPS_XENON_TIME')),
                   Int(name='hgcd', help='HgCd lamp request time',
                       FITS=('W_CLHGCT', 'PFILAMPS_HGCD_TIME')),
                   Int(name='cont', help='Halogen lamp request time',
                       FITS=('W_CLQTHT', 'PFILAMPS_HALOGEN_TIME'))),
               Key('halogen',
                   Bool('off', 'on', name='state', help='Halogen lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
               Key('neon',
                   Bool('off', 'on', name='state', help='Neon lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
               Key('argon',
                   Bool('off', 'on', name='state', help='Argon lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('krypton',
                   Bool('off', 'on', name='state', help='Krypton lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('xenon',
                   Bool('off', 'on', name='state', help='Xenon lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
                Key('hgcd',
                   Bool('off', 'on', name='state', help='HgCd lamp state'),
                   String(name='offTime', help='timestamp when lamp turned off'),
                   String(name='onTime', help='timestamp when lamp turned on')),
 



 
)
