KeysDictionary('rough', (1, 2),
               Key("text",
                   String(help="text for humans")),
               Key("version",
                   String(help="EUPS/git version")),

               Key('pumpSpeed',
                   Float(help='roughing pump speed',
                         units='rpm')),
               Key('pumpTemp',
                   Float(help='roughing pump temperature',
                         units='degC')),
               Key('pumpStatus',
                   Uint(name='mask', help='roughing pump status mask',
                        reprFmt='0x%04x'),
                   String(help='roughing pump status description')),
               Key('pumpWarnings',
                   Uint(name='mask', help='roughing pump warnings mask',
                        reprFmt='0x%02x'),
                   String(help='roughing pump warnings description')),
               Key('pumpErrors',
                   Uint(name='mask', help='roughing pump error mask',
                        reprFmt='0x%2x'),
                   String(help='roughing pump error description')),

               Key('pumpTimes',
                   Int(help='roughing pump cycle count'),
                   Int(help='roughing pump power on time', units='hour'),
                   Int(help='roughing pump pumping time', units='hour')),
               Key('pumpLife',
                   Int(help='roughing pump controller life', units='hour'),
                   Int(help='roughing pump tip seal life', units='hour'),
                   Int(help='roughing pump bearing life', units='hour')),

               Key('pressure',
                   Float(help='roughing line pressure',
                         units='Torr')),
)
