KeysDictionary('spsait', (1, 1),
               Key("text", String(help="text for humans")),
               Key("newExperiment",
                   Int(name='experimentId'),
                   String(name='exptype'),
                   String(name='name'),
                   String(name='comments'),
                   String(name='cmdList'),
                   help='new experiment'),
               Key("newVisits", Int() * (1,),help='new visits'),
               Key("subCommand",
                   Int(name='subCommandId'),
                   String(name='return'),
                   help='new subCommand'),
)
