KeysDictionary(
    'vlan',
    (1, 1),
    Key('text', String(), help='Human oriented message string',),
    Key('version', String(), help='Actor version string',),
    Key('vgw',
        Bool('0', '1', name='output'),
        Int(name='interval'),
        Bool('0', '1', name='alarm'),
        help='VGW state',
    ),
    Key('tws1',
        Bool('0', '1', name='output'),
        Int(name='interval'),
        Bool('0', '1', name='alarm'),
        help='TWS1 state',
    ),
    Key('tws2',
        Bool('0', '1', name='output'),
        Int(name='interval'),
        Bool('0', '1', name='alarm'),
        help='TWS2 state',
    ),
)
